project:
  type: website
  output-dir: docs
  resources: 
    - physiology_data.csv
    - bargraphdata.csv
  
#webr: 
#  packages: ['plotrix', 'base64enc', 'stats']
  
website:
  title: "BIO 110 Web Tutorials"
  navbar: 
    left: 
      - Bio110_lesson_one.qmd
      - Bio110_lesson_two.qmd
      - Bio110_lesson_three.qmd 
      - Bio110_lesson_four.qmd
      - Bio110_lesson_five.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    