project:
  type: website
  output-dir: docs
  resources: 
    - physiology_data.csv
    - bargraphdata.csv
    - sampledatastats.csv
    - Boxplot_quartiles.png
    - bioicon.png
  
webr: 
  packages: ['tidyverse', 'plotrix']

favicon: bioicon.png
  
website:
  title: "BIO 110 Web Tutorials"
  navbar: 
    left: 
      - Bio110_lesson_one.qmd
      - Bio110_lesson_two.qmd
      - Bio110_lesson_three.qmd 
      - Bio110_lesson_four.qmd
      - Bio110_lesson_five.qmd
      - Bio110_lesson_six.qmd
      - Bio110_lesson_seven.qmd
      - Bio110_cheatsheet.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    