project:
  type: website
  output-dir: docs
  resources: 
    - physiology_data.csv
    - bargraphdata.csv
    - sampledatastats.csv
    - Boxplot_quartiles.png
    - bioicon.png
  
webr: 
  packages: ['tidyverse', 'plotrix']
number-sections: true
  
website:
  title: "BIO 110 Web Tutorials"
  favicon: bioicon.png
  sidebar:
    style: "docked"
    contents: 
      - href: Bio110_lesson_one.qmd
      - href: Bio110_lesson_two.qmd
      - href: Bio110_lesson_three.qmd 
      - href: Bio110_lesson_four.qmd
      - href: Bio110_lesson_five.qmd
      - href: Bio110_lesson_six.qmd
      - href: Bio110_lesson_seven.qmd
      - href: Bio110_cheatsheet.qmd
      - href: Bio110_practice.qmd
#      - progressive_tutorial_experimentation/Bio110_test.qmd
#      - progressive_tutorial_experimentation/Bio110_test2.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    